# Generated by Django 6.0.5 on 2026-06-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuardPass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ex_accounts',
            name='bio',
            field=models.CharField(max_length=10),
        ),
    ]
