# Generated by Django 6.0.5 on 2026-06-06 00:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuardPass', '0003_alter_ex_accounts_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ex_accounts',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
