# Generated by Django 6.0.5 on 2026-06-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuardPass', '0004_alter_ex_accounts_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ex_accounts',
            name='Password',
            field=models.BinaryField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ex_accounts',
            name='UserName',
            field=models.BinaryField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ex_accounts',
            name='bio',
            field=models.BinaryField(max_length=10),
        ),
    ]
